<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BootstrapBlazor" Version="10.2.3" />
    <PackageReference Include="BootstrapBlazor.BootstrapIcon" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.12" />
  </ItemGroup>

</Project>
