name: Close all incoming PRs
on:
  # Se déclenche dès l'ouverture de la PR, même depuis un fork
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write  # strictement ce qu'il faut pour commenter/fermer

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          pr-comment: >
            Merci pour la contribution ! Ce dépôt n’accepte pas de Pull Requests.
            Veuillez utiliser les *Issues* pour vos retours et demandes.
          lock-pr: true
